#!/usr/bin/env zsh

emulate zsh -o err_exit

() {
  local url='https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh'
  local installer=${url:t}
  local dir="$HOME/.cache/zsh4humans/v5/Farid-NL/miniconda-z4h/miniconda"
  cd -- ${ZSH_SCRIPT:h}
  wget -q -- $url
  bash -- $installer -b -u -p $dir > /dev/null
  mv $dir ${ZSH_SCRIPT:h}
  rm -- $installer
}
